[profile.default]
solc_version = '0.8.24'
evm_version = 'cancun'
src = 'contracts'
out = "out"
libs = ["node_modules", "lib"]
test = 'test'
cache_path  = 'cache_forge'

remappings = [
  "@/contracts/=contracts/",
]

[fuzz]
runs = 50
